#!/usr/bin/python3

import argparse
from resources.Check import Check

parser = argparse.ArgumentParser(
  description='Convertator',
  formatter_class=argparse.RawDescriptionHelpFormatter,
  prog="convertator",
  usage= "convertator [options] ./path1 ./path2")

# parser.add_argument("-s", "--serialize", action="store_const", 
#   const=CheckSerialize, default=CheckDeserialize, 
#   help="serialize(without deserialize).")
parser.add_argument("-f", "--file", action="store_const", 
  const=True, default=False,
  help="write in the file.")

parser.add_argument("path1", type=str, 
  help="path to original file")
parser.add_argument("path2", type=str,
  help="path to file for convertetion")

args = parser.parse_args()
# print(args)
Check(args)